apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167656665
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167656665
    app.kubernetes.io/part-of: test-app-167656665
  name: java-quarkus-167656665
  namespace: skhileri-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167656665
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167656665
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ebd5e28ebd59123a8aa2743219f574c7bc4dd29166d54107b69f1d791244d445
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
